name: 'SimpleCov_Coverage difference results'
description: 'Creates a comment in the pull-request comparing two SimpleCov resultset files.'
author: Kazuki Nishikawa, Patrick Barattin
inputs:
  base-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the base branch'
    required: true
  head-resultset-path:
    description: 'SimpleCov generated "resultset.json" file path from the head branch'
    required: true
  token:
    description: 'Github generated token (optional - if not provided, runs in dry-run mode)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
